# Configurações do Gateway
spring:
  application:
    name: gateway-service

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: INFO

# Exemplo de rotas
spring:
  cloud:
    gateway:
      routes:
        - id: discovery
          uri: http://localhost:8761
          predicates:
            - Path=/discovery/**
